### PR TITLE
Dockerfile updated to pass all the Red Hat Certification requirements

### PR DESCRIPTION
**Pull request by manojjahgirdar**
The Dockerfile now passes all the following Tests on Red Hat Certification:
- [x] `is_rhel`
- [x] `has_licenses`
- [x] `rpm_list_successful`
- [x] `not_running_privileged`
- [x] `not_running_as_root`
- [x] `name_label_exists`
- [x] `vendor_label_exists`
- [x] `version_label_exists`
- [x] `release_label_exists`
- [x] `good_tags`
- [x] `good_layer_count`
- [x] `free_of_critical_vulnerabilities`
- [x] `free_of_important_vulnerabilities`
- [x] `non_inherited_base_label_name`
- [x] `non_inherited_base_label_vendor`
- [x] `non_inherited_base_label_description`
- [x] `non_inherited_base_label_summary`
- [x] `has_base_rh_image`
- [x] `ubi_content_ok`
- [x] `has_under_40_layers`

>Note: At times the tests `free_of_critical_vulnerabilities` or `free_of_important_vulnerabilities` may fail if the `ubi8/nodejs-12` has any [known vulnerability](https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?gti-tabs=unauthenticated&container-tabs=security).

### CODE REVIEW

**Comment by bwoolf1** [comment]
LGTM. Nice job.

@csantanapr:
- This is built from ubi8/nodejs-12 (was nodejs-10!). Do you want to build it from ubi8/nodejs-14?
- Do you want the security update command commented out or not commented out by default?
- What do you think of the default values for version and release being the same as those for the UBI the image is built from?

**Comment by bwoolf1** [comment]
@csantanapr: What updates do you want to this PR to approve it? Please document these requests for @manojjahgirdar. Thanks.

**Comment by manojjahgirdar** [comment]
- I have commented the updating image security content command.
- I have updated the base image to `ubi8/nodejs14:1-28`.
- Here is a confirmation that the Dockerfile builds successfully after the improvements:
Screenshot 2021-05-05 at 1 33 33 PM

**Comment by csantanapr** [comment]
Can you run the angular app to see there are no problems with nodejs14? 

You can build and deploy the app using the Toolkit? This will verify when you open the app running on OpenShift

**Comment by manojjahgirdar** [comment]
> Can you run the angular app to see there are no problems with nodejs14?
> 
> You can build and deploy the app using the Toolkit? This will verify when you open the app running on OpenShift

@csantanapr,
 
Yes I'm able to run the application on `localhost:3000`. I'm trying to build and deploy using Toolkit on Openshift. When I run the `oc pipeline` command I'm getting this error: 
```
Error registering pipeline: conversion webhook for tekton.dev/v1beta1, Kind=Pipeline failed: Post https://tekton-pipelines-webhook.openshift-pipelines.svc:443/resource-conversion?timeout=30s: dial tcp 172.17.3.79:8443: connect: connection timed out
```
not sure what to do here.

**Comment by manojjahgirdar** [comment]
> > Can you run the angular app to see there are no problems with nodejs14?
> > You can build and deploy the app using the Toolkit? This will verify when you open the app running on OpenShift
> 
> @csantanapr,
> 
> Yes I'm able to run the application on `localhost:3000`. I'm trying to build and deploy using Toolkit on Openshift. When I run the `oc pipeline` command I'm getting this error:
> 
> ```
> Error registering pipeline: conversion webhook for tekton.dev/v1beta1, Kind=Pipeline failed: Post https://tekton-pipelines-webhook.openshift-pipelines.svc:443/resource-conversion?timeout=30s: dial tcp 172.17.3.79:8443: connect: connection timed out
> ```
> 
> not sure what to do here.

I ran this test again .This passes all the tests except for the `gitops` one. The logs says the following:
```
unable to find result referenced by param "helm-url" in "gitops": Could not find result with name helm-url for task run helm-release
```
Screenshot 2021-05-06 at 1 04 16 AM

what does this mean?

**Comment by manojjahgirdar** [comment]
@csantanapr, Here is the verification that the app still works on OpenShift, using the Toolkit pipeline to build and deploy.

Screenshot 2021-05-06 at 11 53 47 PM

**Review by csantanapr — CHANGES_REQUESTED** [review]
There is a problem in the tekton pipeline test task is failing with nodejs14

**Comment by csantanapr** [comment]
There is problem in the pipeline while testing this change
image

**Comment by csantanapr** [comment]
Even without this change the App looks like is broken.
```
npm WARN tar ENOENT: no such file or directory, open '/source/node_modules/.staging/carbon-components-8b321cf4/css/carbon-components.css.map'
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404
npm ERR! 404 'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'source'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR! /tekton/home/.npm/_logs/2021-05-13T05_20_48_760Z-debug.log
```

I suspect is that the test task uses a new version of node and is not compatible

**Review by csantanapr — APPROVED** [review]

**Comment by csantanapr** [comment]
I was able to get farther using the new `ibm-general` pipeline that doesn't include unit tests

**Comment by csantanapr** [comment]
Well the app it doesn't even run today 
image

**Pull request merged**
